package com.servicemesh.agility.tools.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * This annotation allows for annotation of Java properties.  The majority of the information about
 * a field is gleaned through reflection.  This is also used in schema definitions to annotation classes
 * generated by JAXB.
 * 
 * @author henry
 *
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface ApiField {
   String  comment()         default "";
   boolean systemGenerated() default false;
   String  allowableValues() default "";
   String  introducedIn()    default "";
}
