package com.servicemesh.agility.tools.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * This annotation is used to document the return object, if any, generated by the action.  Multiple responses
 * can be returned by an action.  Each can be listed.  It is acceptable for multiple responses with the same
 * code to be used.
 * 
 * The containerType property is used document that multiple objects are needed.  Valid values represent Java
 * types such as ARRAY, LIST, SET.

 * @author henry
 *
 */

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.ANNOTATION_TYPE)
public @interface ApiResponse {
   String  comment()         default "";
   String  dataType();
   String  containerType()   default "";
   String  responseCode();
   String  message()         default "";
}
